# Generated by Django 5.2.7 on 2025-11-04 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id_manutencao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dia_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'manutencao',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('senha', models.CharField(max_length=512)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=15)),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marca', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
        migrations.CreateModel(
            name='Manutencao_realizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manutencao')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.veiculo')),
            ],
            options={
                'db_table': 'manutencao_realizada',
            },
        ),
        migrations.CreateModel(
            name='Viagem_realizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'viagem_realizada',
            },
        ),
    ]
